// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package futures

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures(in *jlexer.Lexer, out *Balance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "accountAlias":
			out.AccountAlias = string(in.String())
		case "asset":
			out.Asset = string(in.String())
		case "balance":
			out.Balance = string(in.String())
		case "crossWalletBalance":
			out.CrossWalletBalance = string(in.String())
		case "crossUnPnl":
			out.CrossUnPnl = string(in.String())
		case "availableBalance":
			out.AvailableBalance = string(in.String())
		case "maxWithdrawAmount":
			out.MaxWithdrawAmount = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures(out *jwriter.Writer, in Balance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountAlias\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountAlias))
	}
	{
		const prefix string = ",\"asset\":"
		out.RawString(prefix)
		out.String(string(in.Asset))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.String(string(in.Balance))
	}
	{
		const prefix string = ",\"crossWalletBalance\":"
		out.RawString(prefix)
		out.String(string(in.CrossWalletBalance))
	}
	{
		const prefix string = ",\"crossUnPnl\":"
		out.RawString(prefix)
		out.String(string(in.CrossUnPnl))
	}
	{
		const prefix string = ",\"availableBalance\":"
		out.RawString(prefix)
		out.String(string(in.AvailableBalance))
	}
	{
		const prefix string = ",\"maxWithdrawAmount\":"
		out.RawString(prefix)
		out.String(string(in.MaxWithdrawAmount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Balance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Balance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Balance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Balance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures(l, v)
}
func easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures1(in *jlexer.Lexer, out *AccountPosition) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "leverage":
			out.Leverage = string(in.String())
		case "initialMargin":
			out.InitialMargin = string(in.String())
		case "maintMargin":
			out.MaintMargin = string(in.String())
		case "openOrderInitialMargin":
			out.OpenOrderInitialMargin = string(in.String())
		case "positionInitialMargin":
			out.PositionInitialMargin = string(in.String())
		case "symbol":
			out.Symbol = string(in.String())
		case "unrealizedProfit":
			out.UnrealizedProfit = string(in.String())
		case "entryPrice":
			out.EntryPrice = string(in.String())
		case "maxNotional":
			out.MaxNotional = string(in.String())
		case "positionAmt":
			out.PositionAmt = string(in.String())
		case "notional":
			out.Notional = string(in.String())
		case "bidNotional":
			out.BidNotional = string(in.String())
		case "askNotional":
			out.AskNotional = string(in.String())
		case "positionSide":
			out.PositionSide = PositionSideType(in.String())
		case "updateTime":
			out.UpdateTime = int64(in.Int64())
		case "isolated":
			out.Isolated = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures1(out *jwriter.Writer, in AccountPosition) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"leverage\":"
		out.RawString(prefix[1:])
		out.String(string(in.Leverage))
	}
	{
		const prefix string = ",\"initialMargin\":"
		out.RawString(prefix)
		out.String(string(in.InitialMargin))
	}
	{
		const prefix string = ",\"maintMargin\":"
		out.RawString(prefix)
		out.String(string(in.MaintMargin))
	}
	{
		const prefix string = ",\"openOrderInitialMargin\":"
		out.RawString(prefix)
		out.String(string(in.OpenOrderInitialMargin))
	}
	{
		const prefix string = ",\"positionInitialMargin\":"
		out.RawString(prefix)
		out.String(string(in.PositionInitialMargin))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"unrealizedProfit\":"
		out.RawString(prefix)
		out.String(string(in.UnrealizedProfit))
	}
	{
		const prefix string = ",\"entryPrice\":"
		out.RawString(prefix)
		out.String(string(in.EntryPrice))
	}
	{
		const prefix string = ",\"maxNotional\":"
		out.RawString(prefix)
		out.String(string(in.MaxNotional))
	}
	{
		const prefix string = ",\"positionAmt\":"
		out.RawString(prefix)
		out.String(string(in.PositionAmt))
	}
	{
		const prefix string = ",\"notional\":"
		out.RawString(prefix)
		out.String(string(in.Notional))
	}
	{
		const prefix string = ",\"bidNotional\":"
		out.RawString(prefix)
		out.String(string(in.BidNotional))
	}
	{
		const prefix string = ",\"askNotional\":"
		out.RawString(prefix)
		out.String(string(in.AskNotional))
	}
	{
		const prefix string = ",\"positionSide\":"
		out.RawString(prefix)
		out.String(string(in.PositionSide))
	}
	{
		const prefix string = ",\"updateTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdateTime))
	}
	{
		const prefix string = ",\"isolated\":"
		out.RawString(prefix)
		out.Bool(bool(in.Isolated))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountPosition) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountPosition) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountPosition) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountPosition) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures1(l, v)
}
func easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures2(in *jlexer.Lexer, out *AccountBalanceList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(AccountBalanceList, 0, 8)
			} else {
				*out = AccountBalanceList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *Balance
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(Balance)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures2(out *jwriter.Writer, in AccountBalanceList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v AccountBalanceList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountBalanceList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountBalanceList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountBalanceList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures2(l, v)
}
func easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures3(in *jlexer.Lexer, out *AccountAsset) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset":
			out.Asset = string(in.String())
		case "initialMargin":
			out.InitialMargin = string(in.String())
		case "maintMargin":
			out.MaintMargin = string(in.String())
		case "marginBalance":
			out.MarginBalance = string(in.String())
		case "maxWithdrawAmount":
			out.MaxWithdrawAmount = string(in.String())
		case "openOrderInitialMargin":
			out.OpenOrderInitialMargin = string(in.String())
		case "positionInitialMargin":
			out.PositionInitialMargin = string(in.String())
		case "unrealizedProfit":
			out.UnrealizedProfit = string(in.String())
		case "walletBalance":
			out.WalletBalance = string(in.String())
		case "crossWalletBalance":
			out.CrossWalletBalance = string(in.String())
		case "crossUnPnl":
			out.CrossUnPnl = string(in.String())
		case "availableBalance":
			out.AvailableBalance = string(in.String())
		case "marginAvailable":
			out.MarginAvailable = bool(in.Bool())
		case "updateTime":
			out.UpdateTime = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures3(out *jwriter.Writer, in AccountAsset) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset))
	}
	{
		const prefix string = ",\"initialMargin\":"
		out.RawString(prefix)
		out.String(string(in.InitialMargin))
	}
	{
		const prefix string = ",\"maintMargin\":"
		out.RawString(prefix)
		out.String(string(in.MaintMargin))
	}
	{
		const prefix string = ",\"marginBalance\":"
		out.RawString(prefix)
		out.String(string(in.MarginBalance))
	}
	{
		const prefix string = ",\"maxWithdrawAmount\":"
		out.RawString(prefix)
		out.String(string(in.MaxWithdrawAmount))
	}
	{
		const prefix string = ",\"openOrderInitialMargin\":"
		out.RawString(prefix)
		out.String(string(in.OpenOrderInitialMargin))
	}
	{
		const prefix string = ",\"positionInitialMargin\":"
		out.RawString(prefix)
		out.String(string(in.PositionInitialMargin))
	}
	{
		const prefix string = ",\"unrealizedProfit\":"
		out.RawString(prefix)
		out.String(string(in.UnrealizedProfit))
	}
	{
		const prefix string = ",\"walletBalance\":"
		out.RawString(prefix)
		out.String(string(in.WalletBalance))
	}
	{
		const prefix string = ",\"crossWalletBalance\":"
		out.RawString(prefix)
		out.String(string(in.CrossWalletBalance))
	}
	{
		const prefix string = ",\"crossUnPnl\":"
		out.RawString(prefix)
		out.String(string(in.CrossUnPnl))
	}
	{
		const prefix string = ",\"availableBalance\":"
		out.RawString(prefix)
		out.String(string(in.AvailableBalance))
	}
	{
		const prefix string = ",\"marginAvailable\":"
		out.RawString(prefix)
		out.Bool(bool(in.MarginAvailable))
	}
	{
		const prefix string = ",\"updateTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdateTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountAsset) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountAsset) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountAsset) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountAsset) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures3(l, v)
}
func easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures4(in *jlexer.Lexer, out *Account) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "totalInitialMargin":
			out.TotalInitialMargin = string(in.String())
		case "totalMaintMargin":
			out.TotalMaintMargin = string(in.String())
		case "totalWalletBalance":
			out.TotalWalletBalance = string(in.String())
		case "totalUnrealizedProfit":
			out.TotalUnrealizedProfit = string(in.String())
		case "totalMarginBalance":
			out.TotalMarginBalance = string(in.String())
		case "totalPositionInitialMargin":
			out.TotalPositionInitialMargin = string(in.String())
		case "totalOpenOrderInitialMargin":
			out.TotalOpenOrderInitialMargin = string(in.String())
		case "totalCrossWalletBalance":
			out.TotalCrossWalletBalance = string(in.String())
		case "totalCrossUnPnl":
			out.TotalCrossUnPnl = string(in.String())
		case "availableBalance":
			out.AvailableBalance = string(in.String())
		case "maxWithdrawAmount":
			out.MaxWithdrawAmount = string(in.String())
		case "assets":
			if in.IsNull() {
				in.Skip()
				out.Assets = nil
			} else {
				in.Delim('[')
				if out.Assets == nil {
					if !in.IsDelim(']') {
						out.Assets = make([]*AccountAsset, 0, 8)
					} else {
						out.Assets = []*AccountAsset{}
					}
				} else {
					out.Assets = (out.Assets)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *AccountAsset
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(AccountAsset)
						}
						(*v4).UnmarshalEasyJSON(in)
					}
					out.Assets = append(out.Assets, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "positions":
			if in.IsNull() {
				in.Skip()
				out.Positions = nil
			} else {
				in.Delim('[')
				if out.Positions == nil {
					if !in.IsDelim(']') {
						out.Positions = make([]*AccountPosition, 0, 8)
					} else {
						out.Positions = []*AccountPosition{}
					}
				} else {
					out.Positions = (out.Positions)[:0]
				}
				for !in.IsDelim(']') {
					var v5 *AccountPosition
					if in.IsNull() {
						in.Skip()
						v5 = nil
					} else {
						if v5 == nil {
							v5 = new(AccountPosition)
						}
						(*v5).UnmarshalEasyJSON(in)
					}
					out.Positions = append(out.Positions, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "updateTime":
			out.UpdateTime = int64(in.Int64())
		case "feeTier":
			out.FeeTier = int(in.Int())
		case "canTrade":
			out.CanTrade = bool(in.Bool())
		case "canDeposit":
			out.CanDeposit = bool(in.Bool())
		case "canWithdraw":
			out.CanWithdraw = bool(in.Bool())
		case "multiAssetsMargin":
			out.MultiAssetsMargin = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures4(out *jwriter.Writer, in Account) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"totalInitialMargin\":"
		out.RawString(prefix[1:])
		out.String(string(in.TotalInitialMargin))
	}
	{
		const prefix string = ",\"totalMaintMargin\":"
		out.RawString(prefix)
		out.String(string(in.TotalMaintMargin))
	}
	{
		const prefix string = ",\"totalWalletBalance\":"
		out.RawString(prefix)
		out.String(string(in.TotalWalletBalance))
	}
	{
		const prefix string = ",\"totalUnrealizedProfit\":"
		out.RawString(prefix)
		out.String(string(in.TotalUnrealizedProfit))
	}
	{
		const prefix string = ",\"totalMarginBalance\":"
		out.RawString(prefix)
		out.String(string(in.TotalMarginBalance))
	}
	{
		const prefix string = ",\"totalPositionInitialMargin\":"
		out.RawString(prefix)
		out.String(string(in.TotalPositionInitialMargin))
	}
	{
		const prefix string = ",\"totalOpenOrderInitialMargin\":"
		out.RawString(prefix)
		out.String(string(in.TotalOpenOrderInitialMargin))
	}
	{
		const prefix string = ",\"totalCrossWalletBalance\":"
		out.RawString(prefix)
		out.String(string(in.TotalCrossWalletBalance))
	}
	{
		const prefix string = ",\"totalCrossUnPnl\":"
		out.RawString(prefix)
		out.String(string(in.TotalCrossUnPnl))
	}
	{
		const prefix string = ",\"availableBalance\":"
		out.RawString(prefix)
		out.String(string(in.AvailableBalance))
	}
	{
		const prefix string = ",\"maxWithdrawAmount\":"
		out.RawString(prefix)
		out.String(string(in.MaxWithdrawAmount))
	}
	{
		const prefix string = ",\"assets\":"
		out.RawString(prefix)
		if in.Assets == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.Assets {
				if v6 > 0 {
					out.RawByte(',')
				}
				if v7 == nil {
					out.RawString("null")
				} else {
					(*v7).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"positions\":"
		out.RawString(prefix)
		if in.Positions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Positions {
				if v8 > 0 {
					out.RawByte(',')
				}
				if v9 == nil {
					out.RawString("null")
				} else {
					(*v9).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"updateTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdateTime))
	}
	{
		const prefix string = ",\"feeTier\":"
		out.RawString(prefix)
		out.Int(int(in.FeeTier))
	}
	{
		const prefix string = ",\"canTrade\":"
		out.RawString(prefix)
		out.Bool(bool(in.CanTrade))
	}
	{
		const prefix string = ",\"canDeposit\":"
		out.RawString(prefix)
		out.Bool(bool(in.CanDeposit))
	}
	{
		const prefix string = ",\"canWithdraw\":"
		out.RawString(prefix)
		out.Bool(bool(in.CanWithdraw))
	}
	{
		const prefix string = ",\"multiAssetsMargin\":"
		out.RawString(prefix)
		out.Bool(bool(in.MultiAssetsMargin))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Account) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Account) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson49f82dd3EncodeGithubComDimkusGoBinanceV2Futures4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Account) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Account) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson49f82dd3DecodeGithubComDimkusGoBinanceV2Futures4(l, v)
}
