// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package futures

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures(in *jlexer.Lexer, out *Symbol) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "underlyingType":
			out.UnderlyingType = string(in.String())
		case "symbol":
			out.Symbol = string(in.String())
		case "contractType":
			out.ContractType = ContractType(in.String())
		case "marketTakeBound":
			out.MarketTakeBound = string(in.String())
		case "liquidationFee":
			out.LiquidationFee = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "baseAsset":
			out.BaseAsset = string(in.String())
		case "requiredMarginPercent":
			out.RequiredMarginPercent = string(in.String())
		case "marginAsset":
			out.MarginAsset = string(in.String())
		case "quoteAsset":
			out.QuoteAsset = string(in.String())
		case "pair":
			out.Pair = string(in.String())
		case "maintMarginPercent":
			out.MaintMarginPercent = string(in.String())
		case "triggerProtect":
			out.TriggerProtect = string(in.String())
		case "underlyingSubType":
			if in.IsNull() {
				in.Skip()
				out.UnderlyingSubType = nil
			} else {
				in.Delim('[')
				if out.UnderlyingSubType == nil {
					if !in.IsDelim(']') {
						out.UnderlyingSubType = make([]string, 0, 4)
					} else {
						out.UnderlyingSubType = []string{}
					}
				} else {
					out.UnderlyingSubType = (out.UnderlyingSubType)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.UnderlyingSubType = append(out.UnderlyingSubType, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "orderType":
			if in.IsNull() {
				in.Skip()
				out.OrderType = nil
			} else {
				in.Delim('[')
				if out.OrderType == nil {
					if !in.IsDelim(']') {
						out.OrderType = make([]OrderType, 0, 4)
					} else {
						out.OrderType = []OrderType{}
					}
				} else {
					out.OrderType = (out.OrderType)[:0]
				}
				for !in.IsDelim(']') {
					var v2 OrderType
					v2 = OrderType(in.String())
					out.OrderType = append(out.OrderType, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "timeInForce":
			if in.IsNull() {
				in.Skip()
				out.TimeInForce = nil
			} else {
				in.Delim('[')
				if out.TimeInForce == nil {
					if !in.IsDelim(']') {
						out.TimeInForce = make([]TimeInForceType, 0, 4)
					} else {
						out.TimeInForce = []TimeInForceType{}
					}
				} else {
					out.TimeInForce = (out.TimeInForce)[:0]
				}
				for !in.IsDelim(']') {
					var v3 TimeInForceType
					v3 = TimeInForceType(in.String())
					out.TimeInForce = append(out.TimeInForce, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "filters":
			if in.IsNull() {
				in.Skip()
				out.Filters = nil
			} else {
				in.Delim('[')
				if out.Filters == nil {
					if !in.IsDelim(']') {
						out.Filters = make([]map[string]interface{}, 0, 8)
					} else {
						out.Filters = []map[string]interface{}{}
					}
				} else {
					out.Filters = (out.Filters)[:0]
				}
				for !in.IsDelim(']') {
					var v4 map[string]interface{}
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						v4 = make(map[string]interface{})
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v5 interface{}
							if m, ok := v5.(easyjson.Unmarshaler); ok {
								m.UnmarshalEasyJSON(in)
							} else if m, ok := v5.(json.Unmarshaler); ok {
								_ = m.UnmarshalJSON(in.Raw())
							} else {
								v5 = in.Interface()
							}
							(v4)[key] = v5
							in.WantComma()
						}
						in.Delim('}')
					}
					out.Filters = append(out.Filters, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "settlePlan":
			out.SettlePlan = int64(in.Int64())
		case "baseAssetPrecision":
			out.BaseAssetPrecision = int(in.Int())
		case "quantityPrecision":
			out.QuantityPrecision = int(in.Int())
		case "pricePrecision":
			out.PricePrecision = int(in.Int())
		case "quotePrecision":
			out.QuotePrecision = int(in.Int())
		case "onboardDate":
			out.OnboardDate = int64(in.Int64())
		case "deliveryDate":
			out.DeliveryDate = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures(out *jwriter.Writer, in Symbol) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"underlyingType\":"
		out.RawString(prefix[1:])
		out.String(string(in.UnderlyingType))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"contractType\":"
		out.RawString(prefix)
		out.String(string(in.ContractType))
	}
	{
		const prefix string = ",\"marketTakeBound\":"
		out.RawString(prefix)
		out.String(string(in.MarketTakeBound))
	}
	{
		const prefix string = ",\"liquidationFee\":"
		out.RawString(prefix)
		out.String(string(in.LiquidationFee))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"baseAsset\":"
		out.RawString(prefix)
		out.String(string(in.BaseAsset))
	}
	{
		const prefix string = ",\"requiredMarginPercent\":"
		out.RawString(prefix)
		out.String(string(in.RequiredMarginPercent))
	}
	{
		const prefix string = ",\"marginAsset\":"
		out.RawString(prefix)
		out.String(string(in.MarginAsset))
	}
	{
		const prefix string = ",\"quoteAsset\":"
		out.RawString(prefix)
		out.String(string(in.QuoteAsset))
	}
	{
		const prefix string = ",\"pair\":"
		out.RawString(prefix)
		out.String(string(in.Pair))
	}
	{
		const prefix string = ",\"maintMarginPercent\":"
		out.RawString(prefix)
		out.String(string(in.MaintMarginPercent))
	}
	{
		const prefix string = ",\"triggerProtect\":"
		out.RawString(prefix)
		out.String(string(in.TriggerProtect))
	}
	{
		const prefix string = ",\"underlyingSubType\":"
		out.RawString(prefix)
		if in.UnderlyingSubType == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.UnderlyingSubType {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"orderType\":"
		out.RawString(prefix)
		if in.OrderType == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.OrderType {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"timeInForce\":"
		out.RawString(prefix)
		if in.TimeInForce == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.TimeInForce {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"filters\":"
		out.RawString(prefix)
		if in.Filters == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Filters {
				if v12 > 0 {
					out.RawByte(',')
				}
				if v13 == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v14First := true
					for v14Name, v14Value := range v13 {
						if v14First {
							v14First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v14Name))
						out.RawByte(':')
						if m, ok := v14Value.(easyjson.Marshaler); ok {
							m.MarshalEasyJSON(out)
						} else if m, ok := v14Value.(json.Marshaler); ok {
							out.Raw(m.MarshalJSON())
						} else {
							out.Raw(json.Marshal(v14Value))
						}
					}
					out.RawByte('}')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"settlePlan\":"
		out.RawString(prefix)
		out.Int64(int64(in.SettlePlan))
	}
	{
		const prefix string = ",\"baseAssetPrecision\":"
		out.RawString(prefix)
		out.Int(int(in.BaseAssetPrecision))
	}
	{
		const prefix string = ",\"quantityPrecision\":"
		out.RawString(prefix)
		out.Int(int(in.QuantityPrecision))
	}
	{
		const prefix string = ",\"pricePrecision\":"
		out.RawString(prefix)
		out.Int(int(in.PricePrecision))
	}
	{
		const prefix string = ",\"quotePrecision\":"
		out.RawString(prefix)
		out.Int(int(in.QuotePrecision))
	}
	{
		const prefix string = ",\"onboardDate\":"
		out.RawString(prefix)
		out.Int64(int64(in.OnboardDate))
	}
	{
		const prefix string = ",\"deliveryDate\":"
		out.RawString(prefix)
		out.Int64(int64(in.DeliveryDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Symbol) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Symbol) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Symbol) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Symbol) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures1(in *jlexer.Lexer, out *RateLimit) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "rateLimitType":
			out.RateLimitType = string(in.String())
		case "interval":
			out.Interval = string(in.String())
		case "intervalNum":
			out.IntervalNum = int64(in.Int64())
		case "limit":
			out.Limit = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures1(out *jwriter.Writer, in RateLimit) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rateLimitType\":"
		out.RawString(prefix[1:])
		out.String(string(in.RateLimitType))
	}
	{
		const prefix string = ",\"interval\":"
		out.RawString(prefix)
		out.String(string(in.Interval))
	}
	{
		const prefix string = ",\"intervalNum\":"
		out.RawString(prefix)
		out.Int64(int64(in.IntervalNum))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RateLimit) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RateLimit) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RateLimit) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RateLimit) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures1(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures2(in *jlexer.Lexer, out *PriceFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "maxPrice":
			out.MaxPrice = string(in.String())
		case "minPrice":
			out.MinPrice = string(in.String())
		case "tickSize":
			out.TickSize = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures2(out *jwriter.Writer, in PriceFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"maxPrice\":"
		out.RawString(prefix[1:])
		out.String(string(in.MaxPrice))
	}
	{
		const prefix string = ",\"minPrice\":"
		out.RawString(prefix)
		out.String(string(in.MinPrice))
	}
	{
		const prefix string = ",\"tickSize\":"
		out.RawString(prefix)
		out.String(string(in.TickSize))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PriceFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PriceFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PriceFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PriceFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures2(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures3(in *jlexer.Lexer, out *PercentPriceFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "multiplierDecimal":
			out.MultiplierDecimal = string(in.String())
		case "multiplierUp":
			out.MultiplierUp = string(in.String())
		case "multiplierDown":
			out.MultiplierDown = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures3(out *jwriter.Writer, in PercentPriceFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"multiplierDecimal\":"
		out.RawString(prefix[1:])
		out.String(string(in.MultiplierDecimal))
	}
	{
		const prefix string = ",\"multiplierUp\":"
		out.RawString(prefix)
		out.String(string(in.MultiplierUp))
	}
	{
		const prefix string = ",\"multiplierDown\":"
		out.RawString(prefix)
		out.String(string(in.MultiplierDown))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PercentPriceFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PercentPriceFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PercentPriceFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PercentPriceFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures3(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures4(in *jlexer.Lexer, out *MinNotionalFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "notional":
			out.Notional = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures4(out *jwriter.Writer, in MinNotionalFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"notional\":"
		out.RawString(prefix[1:])
		out.String(string(in.Notional))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MinNotionalFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MinNotionalFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MinNotionalFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MinNotionalFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures4(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures5(in *jlexer.Lexer, out *MaxNumOrdersFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "limit":
			out.Limit = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures5(out *jwriter.Writer, in MaxNumOrdersFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Limit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MaxNumOrdersFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MaxNumOrdersFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MaxNumOrdersFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MaxNumOrdersFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures5(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures6(in *jlexer.Lexer, out *MaxNumAlgoOrdersFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "limit":
			out.Limit = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures6(out *jwriter.Writer, in MaxNumAlgoOrdersFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Limit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MaxNumAlgoOrdersFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MaxNumAlgoOrdersFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MaxNumAlgoOrdersFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MaxNumAlgoOrdersFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures6(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures7(in *jlexer.Lexer, out *MarketLotSizeFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "maxQty":
			out.MaxQuantity = string(in.String())
		case "minQty":
			out.MinQuantity = string(in.String())
		case "stepSize":
			out.StepSize = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures7(out *jwriter.Writer, in MarketLotSizeFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"maxQty\":"
		out.RawString(prefix[1:])
		out.String(string(in.MaxQuantity))
	}
	{
		const prefix string = ",\"minQty\":"
		out.RawString(prefix)
		out.String(string(in.MinQuantity))
	}
	{
		const prefix string = ",\"stepSize\":"
		out.RawString(prefix)
		out.String(string(in.StepSize))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MarketLotSizeFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MarketLotSizeFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MarketLotSizeFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MarketLotSizeFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures7(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures8(in *jlexer.Lexer, out *LotSizeFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "maxQty":
			out.MaxQuantity = string(in.String())
		case "minQty":
			out.MinQuantity = string(in.String())
		case "stepSize":
			out.StepSize = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures8(out *jwriter.Writer, in LotSizeFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"maxQty\":"
		out.RawString(prefix[1:])
		out.String(string(in.MaxQuantity))
	}
	{
		const prefix string = ",\"minQty\":"
		out.RawString(prefix)
		out.String(string(in.MinQuantity))
	}
	{
		const prefix string = ",\"stepSize\":"
		out.RawString(prefix)
		out.String(string(in.StepSize))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LotSizeFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LotSizeFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LotSizeFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LotSizeFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures8(l, v)
}
func easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures9(in *jlexer.Lexer, out *ExchangeInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "timezone":
			out.Timezone = string(in.String())
		case "rateLimits":
			if in.IsNull() {
				in.Skip()
				out.RateLimits = nil
			} else {
				in.Delim('[')
				if out.RateLimits == nil {
					if !in.IsDelim(']') {
						out.RateLimits = make([]RateLimit, 0, 1)
					} else {
						out.RateLimits = []RateLimit{}
					}
				} else {
					out.RateLimits = (out.RateLimits)[:0]
				}
				for !in.IsDelim(']') {
					var v15 RateLimit
					(v15).UnmarshalEasyJSON(in)
					out.RateLimits = append(out.RateLimits, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "exchangeFilters":
			if in.IsNull() {
				in.Skip()
				out.ExchangeFilters = nil
			} else {
				in.Delim('[')
				if out.ExchangeFilters == nil {
					if !in.IsDelim(']') {
						out.ExchangeFilters = make([]interface{}, 0, 4)
					} else {
						out.ExchangeFilters = []interface{}{}
					}
				} else {
					out.ExchangeFilters = (out.ExchangeFilters)[:0]
				}
				for !in.IsDelim(']') {
					var v16 interface{}
					if m, ok := v16.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v16.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v16 = in.Interface()
					}
					out.ExchangeFilters = append(out.ExchangeFilters, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "symbols":
			if in.IsNull() {
				in.Skip()
				out.Symbols = nil
			} else {
				in.Delim('[')
				if out.Symbols == nil {
					if !in.IsDelim(']') {
						out.Symbols = make([]Symbol, 0, 0)
					} else {
						out.Symbols = []Symbol{}
					}
				} else {
					out.Symbols = (out.Symbols)[:0]
				}
				for !in.IsDelim(']') {
					var v17 Symbol
					(v17).UnmarshalEasyJSON(in)
					out.Symbols = append(out.Symbols, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "serverTime":
			out.ServerTime = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures9(out *jwriter.Writer, in ExchangeInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timezone\":"
		out.RawString(prefix[1:])
		out.String(string(in.Timezone))
	}
	{
		const prefix string = ",\"rateLimits\":"
		out.RawString(prefix)
		if in.RateLimits == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.RateLimits {
				if v18 > 0 {
					out.RawByte(',')
				}
				(v19).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"exchangeFilters\":"
		out.RawString(prefix)
		if in.ExchangeFilters == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.ExchangeFilters {
				if v20 > 0 {
					out.RawByte(',')
				}
				if m, ok := v21.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v21.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v21))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"symbols\":"
		out.RawString(prefix)
		if in.Symbols == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v22, v23 := range in.Symbols {
				if v22 > 0 {
					out.RawByte(',')
				}
				(v23).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"serverTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ServerTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExchangeInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExchangeInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94abd26cEncodeGithubComDimkusGoBinanceV2Futures9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExchangeInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExchangeInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94abd26cDecodeGithubComDimkusGoBinanceV2Futures9(l, v)
}
