// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package futures

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures(in *jlexer.Lexer, out *WsMarkPriceEventList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(WsMarkPriceEventList, 0, 8)
			} else {
				*out = WsMarkPriceEventList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *WsMarkPriceEvent
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(WsMarkPriceEvent)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures(out *jwriter.Writer, in WsMarkPriceEventList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v WsMarkPriceEventList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WsMarkPriceEventList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WsMarkPriceEventList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WsMarkPriceEventList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures(l, v)
}
func easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures1(in *jlexer.Lexer, out *WsMarkPriceEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "e":
			out.Event = string(in.String())
		case "s":
			out.Symbol = string(in.String())
		case "p":
			out.MarkPrice = string(in.String())
		case "i":
			out.IndexPrice = string(in.String())
		case "P":
			out.EstimatedSettlePrice = string(in.String())
		case "r":
			out.FundingRate = string(in.String())
		case "E":
			out.Time = int64(in.Int64())
		case "T":
			out.NextFundingTime = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures1(out *jwriter.Writer, in WsMarkPriceEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"e\":"
		out.RawString(prefix[1:])
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"p\":"
		out.RawString(prefix)
		out.String(string(in.MarkPrice))
	}
	{
		const prefix string = ",\"i\":"
		out.RawString(prefix)
		out.String(string(in.IndexPrice))
	}
	{
		const prefix string = ",\"P\":"
		out.RawString(prefix)
		out.String(string(in.EstimatedSettlePrice))
	}
	{
		const prefix string = ",\"r\":"
		out.RawString(prefix)
		out.String(string(in.FundingRate))
	}
	{
		const prefix string = ",\"E\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"T\":"
		out.RawString(prefix)
		out.Int64(int64(in.NextFundingTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WsMarkPriceEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WsMarkPriceEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WsMarkPriceEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WsMarkPriceEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures1(l, v)
}
func easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures2(in *jlexer.Lexer, out *WsBookTickerEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "e":
			out.Event = string(in.String())
		case "s":
			out.Symbol = string(in.String())
		case "b":
			out.BestBidPrice = string(in.String())
		case "B":
			out.BestBidQty = string(in.String())
		case "a":
			out.BestAskPrice = string(in.String())
		case "A":
			out.BestAskQty = string(in.String())
		case "u":
			out.UpdateID = int64(in.Int64())
		case "E":
			out.Time = int64(in.Int64())
		case "T":
			out.TransactionTime = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures2(out *jwriter.Writer, in WsBookTickerEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"e\":"
		out.RawString(prefix[1:])
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"b\":"
		out.RawString(prefix)
		out.String(string(in.BestBidPrice))
	}
	{
		const prefix string = ",\"B\":"
		out.RawString(prefix)
		out.String(string(in.BestBidQty))
	}
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix)
		out.String(string(in.BestAskPrice))
	}
	{
		const prefix string = ",\"A\":"
		out.RawString(prefix)
		out.String(string(in.BestAskQty))
	}
	{
		const prefix string = ",\"u\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdateID))
	}
	{
		const prefix string = ",\"E\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"T\":"
		out.RawString(prefix)
		out.Int64(int64(in.TransactionTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WsBookTickerEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WsBookTickerEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WsBookTickerEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WsBookTickerEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures2(l, v)
}
func easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures3(in *jlexer.Lexer, out *WsAggTradeEventMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				if out.Data == nil {
					out.Data = new(WsAggTradeEvent)
				}
				(*out.Data).UnmarshalEasyJSON(in)
			}
		case "stream":
			out.Stream = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures3(out *jwriter.Writer, in WsAggTradeEventMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix[1:])
		if in.Data == nil {
			out.RawString("null")
		} else {
			(*in.Data).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"stream\":"
		out.RawString(prefix)
		out.String(string(in.Stream))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WsAggTradeEventMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WsAggTradeEventMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WsAggTradeEventMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WsAggTradeEventMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures3(l, v)
}
func easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures4(in *jlexer.Lexer, out *WsAggTradeEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "s":
			out.Symbol = string(in.String())
		case "e":
			out.Event = string(in.String())
		case "p":
			out.Price = string(in.String())
		case "q":
			out.Quantity = string(in.String())
		case "E":
			out.Time = int64(in.Int64())
		case "a":
			out.AggregateTradeID = int64(in.Int64())
		case "f":
			out.FirstTradeID = int64(in.Int64())
		case "l":
			out.LastTradeID = int64(in.Int64())
		case "T":
			out.TradeTime = int64(in.Int64())
		case "m":
			out.Maker = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures4(out *jwriter.Writer, in WsAggTradeEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"e\":"
		out.RawString(prefix)
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"p\":"
		out.RawString(prefix)
		out.String(string(in.Price))
	}
	{
		const prefix string = ",\"q\":"
		out.RawString(prefix)
		out.String(string(in.Quantity))
	}
	{
		const prefix string = ",\"E\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix)
		out.Int64(int64(in.AggregateTradeID))
	}
	{
		const prefix string = ",\"f\":"
		out.RawString(prefix)
		out.Int64(int64(in.FirstTradeID))
	}
	{
		const prefix string = ",\"l\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastTradeID))
	}
	{
		const prefix string = ",\"T\":"
		out.RawString(prefix)
		out.Int64(int64(in.TradeTime))
	}
	{
		const prefix string = ",\"m\":"
		out.RawString(prefix)
		out.Bool(bool(in.Maker))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WsAggTradeEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WsAggTradeEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEd041cfEncodeGithubComDimkusGoBinanceV2Futures4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WsAggTradeEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WsAggTradeEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEd041cfDecodeGithubComDimkusGoBinanceV2Futures4(l, v)
}
